# Generated by Django 5.1 on 2024-08-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='media', upload_to='media'),
            preserve_default=False,
        ),
    ]
